name: MLOPS Pipeline CI

on: [push, pull_request]

jobs:
  M1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          #pip install tensorflow numpy pandas matplotlib pandas-profiling sweetviz
          #pip uninstall pandas-profiling ydata-profiling visions numba -y
          #pip install ydata-profiling visions numba

      - name: Run pipeline
        run: |
          # python src/eda.py
  M2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          #pip install numpy pandas matplotlib seaborn scikit-learn tensorflow lime

      - name: Run pipeline
        run: |
          # python src/explainability.py
  M3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          #pip install numpy pandas matplotlib scikit-learn tensorflow h2o optuna seaborn joblib

      - name: Run pipeline
        run: |
          # python src/automl.py
  M4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          #pip install tensorflow mlflow scikit-learn matplotlib seaborn

      - name: Run pipeline
        run: |
          #python src/performance.py