name: EDA Pipeline

on: [push, pull_request]

jobs:
  sweetviz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow numpy pandas matplotlib pandas-profiling sweetviz
          pip uninstall pandas-profiling ydata-profiling visions numba -y
          pip install ydata-profiling visions numba

      - name: Run pipeline
        run: |
          #python src/eda_sweetviz.py